version: "3.3"
services:
  telegram-bot-bd:
    container_name: telegram-bot-bd
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=selectel
      - POSTGRES_USER=selectel
      - POSTGRES_DB=selectel
    ports:
      - "5434:5432"
  go-server:
    container_name: go-telegram-bot
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./config/test.env
    environment:
      - YARATAM_POSTGRES_PASSWORD=selectel
      - YARATAM_TG_BOT_TOKEN=5517986052:AAH9JGvWfS6erD6NFo4zHnn5ipO9V6I4hYE
      - YARATAM_POSTGRES_PORT=5432
    links:
      - "telegram-bot-bd:pg_db"