CREATE TABLE schema_migrations
(
    version bigint  not null
        primary key,
    dirty   boolean not null
);

CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text UNIQUE ,
    password text,
    accuses_token text ,
    refresh_token text
);

CREATE TABLE app_log
(
    user_id  integer references users (id),
    start_dt timestamp default now(),
    header   text,
    body     text,
    status   int
);
