name: Deployment

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          YARATAM_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          YARATAM_TG_BOT_TOKEN: ${{ secrets.YARATAM_TG_BOT_TOKEN }}
        run: docker-compose -f compose/docker-compose.prod.yaml up
